server:
  port: 9999
  servlet:
    context-path: /druid

#日志输出配置
logging:
  config: classpath:logging/log4j2.yml

spring:
  datasource:
    url: jdbc:mysql://localhost/crawler?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    servlet:
      content-type: text/html;
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML5
    cache: false
  mvc:
      static-path-pattern: /**